context:
  name: television
  version: "0.15.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/alexpasmantier/television/archive/refs/tags/${{ version }}.tar.gz
  sha256: 1e1f9d5c7a4a22b20ce8cf26f3ee4f72fb1361368d759063ea7ff611979be0fb

build:
  number: 0
  skip: ppc64le


requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tv --help

about:
  homepage: https://github.com/alexpasmantier/television
  summary: A blazingly fast general purpose fuzzy finder TUI.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
    - blmaier
