context:
  name: television
  version: "0.13.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/alexpasmantier/television/archive/refs/tags/${{ version }}.tar.gz
  sha256: e882cf587b922e81b1b6d1037e651f3c8e2d5624693855779917a60fc4b79a37

build:
  number: 0


requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tv --help

about:
  homepage: https://github.com/alexpasmantier/television
  summary: A blazingly fast general purpose fuzzy finder TUI.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
    - blmaier
