context:
  name: television
  version: "0.15.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/alexpasmantier/television/archive/refs/tags/${{ version }}.tar.gz
  sha256: 36c97916d7062025697e6268992985e0e7c7f0b458230faaca3735d09c911cca

build:
  number: 0
  skip: ppc64le


requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tv --help

about:
  homepage: https://github.com/alexpasmantier/television
  summary: A blazingly fast general purpose fuzzy finder TUI.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
    - blmaier
